# Generated by Django 4.2.7 on 2023-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_team1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_team2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='À venir', max_length=50),
        ),
    ]
