# Generated by Django 4.2.7 on 2023-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_match_end_time_match_odds_team1_match_odds_team2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default='2023-12-11T15:02:04.560745+00:00'),
        ),
    ]
