# Generated by Django 4.2.7 on 2023-12-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_match_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='odds_team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='odds_team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
    ]
