# Generated by Django 4.2.7 on 2023-12-11 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_match_end_time_remove_match_odds_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='match_starting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
