# Generated by Django 4.2.7 on 2023-12-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_player_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(),
        ),
    ]
