# Generated by Django 4.2.7 on 2023-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_player_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='family_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
