# Generated by Django 4.2.7 on 2023-12-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_player_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('À venir', 'À venir'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='À venir', max_length=50),
        ),
    ]
